### ISSUE TITLE
Sanguino Assistance Needed

### ISSUE THREAD

**Issue by jneilliii** [Booli/OctoPrint-flashArduino#13]
I've used flashArduino without issues on my RAMBo board for a while now and recently added a Melzi board to the mix and have been able to flash firmware from the Arduino IDE in windows, but when running on my OctoPi instance I'm getting an error, listed below.  I'm using the option for Sanguino ATmega 1487p (same I use from windows) from settings. From searching the error I found references to modifying the boards.txt file to tell that 1487p chip to use the arduino programmer, but don't know where that is saved in command line avrdude.  The only difference between the arduino ide I can tell is that the board to select that works is Sanguino w/ ATmega 1487p or ATmega 1487p (16MHz) What am I missing to get this to work?

avrdude: stk500v2_ReceiveMessage(): timeout

**Comment by Salandora** [comment]
@jneilliii you will need to edit the code of flashArduino for this... sadly I never finished the BoardManager otherwise this wouldn't be necessary now..

But look here: 
https://github.com/Leapfrog3DPrinters/OctoPrint-flashArduino/blob/master/octoprint_flasharduino/programmers/avrdude.py#L16

This is what you want to change, the protocol and baudrate should be the things to change.... ,
Also are you sure you have an atmega1487p on it not an 1284p?

**Comment by jneilliii** [comment]
Thanks Salandora, I was able to add another board to the avrdude.py and it works for me now.  Created pull request just in case it might help others.
